# Generated by Django 3.0.5 on 2020-11-14 21:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201106_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=accounts.models.get_or_create_default_tags, to='accounts.Tag', verbose_name='tag'),
        ),
    ]
