# Generated by Django 3.0.5 on 2021-01-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20201201_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
    ]
