# Generated by Django 3.0.5 on 2021-02-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210116_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='point_add',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='point_use',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_before', models.IntegerField(default=0)),
                ('point_use', models.IntegerField(default=0)),
                ('point_add', models.IntegerField(default=0)),
                ('points_after', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Order')),
            ],
        ),
    ]
