# Generated by Django 3.0.5 on 2021-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210204_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='point_add',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='point_use',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='points_after',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='points_before',
            field=models.FloatField(null=True),
        ),
    ]
