# Generated by Django 3.0.5 on 2021-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_pointshistory_points_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='point_add',
        ),
        migrations.RemoveField(
            model_name='order',
            name='point_use',
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
