# Generated by Django 3.0.5 on 2021-02-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210204_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
