# Generated by Django 3.0.5 on 2021-02-04 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210204_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 23, 43, 46, 868025)),
        ),
    ]
