# Generated by Django 3.0.5 on 2021-02-04 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210205_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 0, 7, 15, 196218)),
        ),
    ]
