# Generated by Django 3.0.5 on 2021-02-09 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210205_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='is_zero',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 42, 9, 263358)),
        ),
    ]
