# Generated by Django 3.0.5 on 2021-02-09 02:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 43, 34, 89426)),
        ),
    ]
