# Generated by Django 3.0.5 on 2021-02-09 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210209_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointshistory',
            name='is_zero',
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 47, 46, 320634)),
        ),
    ]
