# Generated by Django 3.0.5 on 2021-02-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210209_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 23, 46, 38, 867789)),
        ),
    ]
