# Generated by Django 3.0.5 on 2021-02-28 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210209_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 15, 33, 32, 559677)),
        ),
        migrations.CreateModel(
            name='ErrorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=200)),
                ('targetCustomer', models.CharField(max_length=200)),
                ('wrongPramaReference', models.CharField(max_length=200)),
                ('errorContent', models.CharField(max_length=1000)),
                ('customerOfUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
            ],
        ),
    ]
